# Generated by Django 5.0.6 on 2024-06-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('UserEmail', models.EmailField(max_length=254)),
                ('UserPassword', models.CharField(max_length=100)),
                ('UserPhone', models.CharField(max_length=11)),
            ],
        ),
    ]
